(() => {
  const api = window.nyan;
  if (!api) return;
  const $ = id => document.getElementById(id);
  let state, speakers = [], initialized = false, toastTimer;
  const labels = { waiting: '待機中', running: '処理中', completed: '完了', failed: '失敗', interrupted: '中断', cancelled: '取消' };
  const fallbackStyles = [{ name: 'ずんだもん', styles: [{ id: 3, name: 'ノーマル' }, { id: 1, name: 'あまあま' }, { id: 7, name: 'ツンツン' }, { id: 5, name: 'セクシー' }, { id: 22, name: 'ささやき' }, { id: 38, name: 'ヒソヒソ' }, { id: 75, name: 'ヘロヘロ' }, { id: 76, name: 'なみだめ' }] }];
  function toast(text, error = false) { $('toast').textContent = text; $('toast').className = error ? 'toast error' : 'toast'; $('toast').hidden = false; clearTimeout(toastTimer); toastTimer = setTimeout(() => { $('toast').hidden = true; }, error ? 12000 : 5000); }
  async function invoke(action, data) { const result = await api.invoke(action, data); if (!result.ok) throw new Error(result.error); return result.value; }
  function task(callback) { return async event => { event?.preventDefault(); const button = event?.currentTarget; if (button?.tagName === 'BUTTON') button.disabled = true; try { await callback(event); } catch (e) { toast(e.message, true); } finally { if (button?.tagName === 'BUTTON') button.disabled = false; } }; }
  function node(tag, text, className) { const e = document.createElement(tag); if (text !== undefined) e.textContent = text; if (className) e.className = className; return e; }
  function button(text, callback) { const e = node('button', text, 'secondary'); e.type = 'button'; e.addEventListener('click', task(callback)); return e; }
  function row(title, detail, controls = []) { const e = node('div', undefined, 'list-row'); const body = node('div', undefined, 'details'); body.append(node('strong', title), node('small', detail)); e.append(body, ...controls); return e; }
  function empty(target, text) { target.replaceChildren(node('p', text, 'subtle')); }
  function getPath(object, path) { return path.split('.').reduce((o, k) => o[k], object); }
  function setPath(object, path, value) { const keys = path.split('.'); const last = keys.pop(); keys.reduce((o, k) => o[k], object)[last] = value; }
  function draft() { const c = structuredClone(state.config); document.querySelectorAll('[data-config]').forEach(input => setPath(c, input.dataset.config, input.type === 'checkbox' ? input.checked : input.hasAttribute('data-number') ? Number(input.value) : input.hasAttribute('data-list') ? input.value.split(/[,\n、]/).map(s => s.trim()).filter(Boolean) : input.value)); return c; }
  function fillConfig() { document.querySelectorAll('[data-config]').forEach(input => { const value = getPath(state.config, input.dataset.config); if (input.type === 'checkbox') input.checked = value; else input.value = Array.isArray(value) ? value.join(', ') : value; }); }
  async function save(c = draft()) { state = await invoke('config:save', c); renderStyles(); fillConfig(); render(state); toast('設定を保存しました'); }
  function navigate(view) { document.querySelectorAll('[data-panel]').forEach(e => { e.hidden = e.dataset.panel !== view; }); document.querySelectorAll('nav [data-view]').forEach(e => e.classList.toggle('active', e.dataset.view === view)); $('page-title').textContent = document.querySelector(`nav [data-view="${view}"]`).textContent.slice(1).trim(); }
  function renderStyles() { const source = speakers.length ? speakers : fallbackStyles; document.querySelectorAll('#style-id,.style-picker').forEach(select => { const previous = select.value || String(state?.config.speech.styleId ?? 3); select.replaceChildren(); for (const speaker of source) { const group = node('optgroup'); group.label = speaker.name; for (const style of speaker.styles.filter(s => !s.type || s.type === 'talk')) { const option = node('option', `${speaker.name}・${style.name}`); option.value = style.id; group.append(option); } select.append(group); } if (![...select.options].some(o => o.value === previous)) { const option = node('option', `声種ID ${previous}`); option.value = previous; select.append(option); } select.value = previous; }); }
  function renderJobs() { if (!state) return; const target = $('job-list'), filter = $('queue-filter').value; target.replaceChildren(); const jobs = state.jobs.filter(j => filter === 'all' || (filter === 'failed' ? ['failed', 'interrupted'].includes(j.status) : j.status === filter)); for (const job of jobs.slice(0, 300)) { const controls = []; if (['waiting', 'running'].includes(job.status)) controls.push(button('取消', async () => render(await invoke('job:action', { id: job.id, action: 'cancel' })))); else controls.push(button('再実行', async () => render(await invoke('job:action', { id: job.id, action: 'retry' })))); target.append(row(`${job.kind === 'media' ? '▶' : '◉'} ${job.payload.title || job.payload.text || job.payload.url}`, `${labels[job.status]} · ${new Date(job.createdAt).toLocaleString('ja-JP')}${job.error ? ` · ${job.error}` : ''}`, controls)); } if (!jobs.length) empty(target, '該当するリクエストはありません。'); }
  function renderCollections() {
    const c = state.config;
    const collections = [
      ['dictionary-list', c.dictionary, d => [d.source + ' → ' + d.replacement, `${d.scope}${d.scopeId ? ': ' + d.scopeId : ''}${d.regex ? ' · 正規表現' : ''}`], (config, d) => { config.dictionary = config.dictionary.filter(x => x.id !== d.id); }],
      ['profile-list', c.speech.profiles, p => [p.name || p.userId, `利用者 ${p.userId} · 声種 ${p.styleId} · 話速 ${p.speed}`], (config, p) => { config.speech.profiles = config.speech.profiles.filter(x => x.userId !== p.userId); }],
      ['clip-list', c.speech.soundClips, p => [p.trigger, p.path], (config, p) => { config.speech.soundClips = config.speech.soundClips.filter(x => x.trigger !== p.trigger); }],
      ['binding-list', c.bot.bindings, b => [b.label || b.guildId, `受信 ${b.textChannelIds.join(', ')} → 音声 ${b.voiceChannelId}`], (config, b) => { config.bot.bindings = config.bot.bindings.filter(x => x.guildId !== b.guildId); }],
    ];
    for (const [id, values, describe, remove] of collections) { const target = $(id); target.replaceChildren(); for (const value of values) { const controls = [button('削除', async () => { const config = draft(); remove(config, value); await save(config); })]; if (id === 'binding-list') controls.unshift(button('参加', async () => render(await invoke('voice:join', value.guildId))), button('退出', async () => render(await invoke('voice:leave', value.guildId)))); target.append(row(...describe(value), controls)); } if (!values.length) empty(target, 'まだ登録されていません。'); }
  }
  function render(next) {
    state = next;
    if (!initialized) { renderStyles(); fillConfig(); initialized = true; }
    const status = { offline: '停止中', connecting: '接続中', online: '接続済み', reconnecting: '再接続中' }[state.bot.status] || state.bot.status;
    $('status-badge').textContent = status; $('status-badge').classList.toggle('mint', state.bot.status === 'online'); $('sidebar-status').textContent = `Bot ${status}`; $('sidebar-dot').classList.toggle('online', state.bot.status === 'online'); $('bot-start').disabled = state.bot.status !== 'offline'; $('bot-stop').disabled = state.bot.status === 'offline'; $('version').textContent = `v${state.version}`;
    $('connection-count').textContent = state.voices.length; $('waiting-count').textContent = state.jobs.filter(j => j.status === 'waiting').length; const today = new Date().toDateString(); $('completed-count').textContent = state.jobs.filter(j => j.status === 'completed' && new Date(j.finishedAt).toDateString() === today).length;
    $('engine-name').textContent = state.config.speech.provider === 'voicevox' ? 'VOICEVOX' : '棒読みちゃん'; $('style-summary').textContent = $('style-id').selectedOptions[0]?.textContent || `声種 ${state.config.speech.styleId}`; $('token-state').textContent = state.tokenSaved ? '保存済み' : '未設定'; $('token-state').classList.toggle('mint', state.tokenSaved); $('token-form').querySelector('button').disabled = !state.vaultAvailable;
    if (!state.vaultAvailable) $('bot-token').placeholder = 'この環境ではOSの暗号化機能を利用できません';
    $('pause-toggle').textContent = state.paused.media || state.paused.speech ? '再開' : '一時停止';
    const current = state.jobs.filter(j => j.status === 'running'); const now = $('now-playing'); now.replaceChildren(); if (current.length) { for (const j of current) now.append(node('strong', j.payload.title || j.payload.text || j.payload.url)); now.append(node('small', state.media ? `再生位置 ${Math.floor(state.media.currentTime || 0)} 秒` : '処理しています')); } else { now.append(node('span', '♫'), node('p', 'リクエストを待っています'), node('small', 'Chrome拡張またはURLフォームから送信できます。')); }
    document.querySelectorAll('.guild-picker').forEach(select => { const value = select.value; select.replaceChildren(node('option', 'サーバー未指定')); select.firstChild.value = ''; for (const b of state.config.bot.bindings) { const option = node('option', b.label || b.guildId); option.value = b.guildId; select.append(option); } select.value = value; });
    const catalog = $('server-catalog'); catalog.replaceChildren(); for (const guild of state.bot.servers) { const detail = node('details'); detail.append(node('summary', `${guild.name} (${guild.id})`)); for (const channel of guild.channels) detail.append(node('p', `${channel.voice ? '音声' : 'テキスト'} #${channel.name} · ${channel.id}`)); catalog.append(detail); } if (!state.bot.servers.length) empty(catalog, 'Botを接続するとサーバー一覧を取得します。');
    renderJobs(); renderCollections(); const logs = $('log-list'); logs.replaceChildren(); for (const entry of state.logs) logs.append(row(entry.text, `${new Date(entry.time).toLocaleTimeString('ja-JP')} · ${entry.level}`)); if (!state.logs.length) empty(logs, 'イベントはまだありません。');
  }
  document.querySelectorAll('[data-view],[data-go]').forEach(e => e.addEventListener('click', () => navigate(e.dataset.view || e.dataset.go)));
  document.querySelectorAll('.save-config').forEach(e => e.addEventListener('click', task(() => save())));
  const actions = { 'bot-start': 'bot:start', 'bot-stop': 'bot:stop', 'show-media': 'media:show', 'open-docs': 'open:docs', 'open-voicevox': 'open:voicevox', 'stop-engine': 'engine:stop', 'export-config': 'config:export' };
  for (const [id, action] of Object.entries(actions)) $(id).addEventListener('click', task(async () => { const value = await invoke(action); if (value?.config) render(value); }));
  $('pause-toggle').addEventListener('click', task(async () => render(await invoke('control', state.paused.media || state.paused.speech ? 'resume' : 'pause'))));
  $('skip-media').addEventListener('click', task(async () => render(await invoke('control', 'skip')))); $('stop-all').addEventListener('click', task(async () => render(await invoke('control', 'stop'))));
  $('token-form').addEventListener('submit', task(async () => { await invoke('token:save', $('bot-token').value); $('bot-token').value = ''; render(await invoke('state')); toast('Botトークンを暗号化して保存しました'); }));
  $('clear-token').addEventListener('click', task(async () => { await invoke('token:clear'); render(await invoke('state')); toast('Botトークンを削除しました'); }));
  $('binding-form').addEventListener('submit', task(async () => { const c = draft(), b = { guildId: $('binding-guild').value.trim(), label: $('binding-label').value.trim(), voiceChannelId: $('binding-voice').value.trim(), textChannelIds: $('binding-text').value.split(/[,\n、]/).map(s => s.trim()).filter(Boolean) }; c.bot.bindings = c.bot.bindings.filter(x => x.guildId !== b.guildId); c.bot.bindings.push(b); await save(c); $('binding-form').reset(); }));
  $('dictionary-form').addEventListener('submit', task(async () => { const c = draft(); c.dictionary.push({ source: $('dict-source').value, replacement: $('dict-replacement').value, scope: $('dict-scope').value, scopeId: $('dict-scope-id').value.trim(), regex: $('dict-regex').checked, caseSensitive: false }); await save(c); $('dictionary-form').reset(); }));
  $('profile-form').addEventListener('submit', task(async () => { const c = draft(), p = { userId: $('profile-id').value.trim(), name: $('profile-name').value, styleId: Number($('profile-style').value), speed: Number($('profile-speed').value) }; c.speech.profiles = c.speech.profiles.filter(x => x.userId !== p.userId); c.speech.profiles.push(p); await save(c); $('profile-form').reset(); }));
  $('choose-clip').addEventListener('click', task(async () => { const path = await invoke('clip:choose'); if (path) $('clip-path').value = path; }));
  $('clip-form').addEventListener('submit', task(async () => { const c = draft(), clip = { trigger: $('clip-trigger').value, path: $('clip-path').value }; c.speech.soundClips = c.speech.soundClips.filter(x => x.trigger !== clip.trigger); c.speech.soundClips.push(clip); await save(c); $('clip-form').reset(); }));
  $('choose-engine').addEventListener('click', task(async () => { const path = await invoke('engine:choose'); if (path) $('engine-executable').value = path; }));
  $('start-engine').addEventListener('click', task(async () => { await save(); render(await invoke('engine:start')); }));
  $('refresh-voices').addEventListener('click', task(async () => { await save(); speakers = await invoke('voices:list'); renderStyles(); toast('声種を読み込みました'); }));
  $('check-styles').addEventListener('click', task(async () => { await save(); const result = await invoke('voices:check', { synthesize: true }); $('voice-check-result').textContent = `${result.styles.length}声種の音声合成を確認しました`; toast('ずんだもん全声種の確認が完了しました'); }));
  $('speech-form').addEventListener('submit', task(async () => { await save(); await invoke('speech:test', { text: $('speech-test').value, guildId: $('speech-guild').value, styleId: Number($('style-id').value) }); toast('読み上げを追加しました'); }));
  $('media-form').addEventListener('submit', task(async () => { await invoke('media:add', { url: $('media-url').value, startSeconds: Number($('media-time').value), loop: $('media-loop').checked, guildId: $('media-guild').value }); $('media-url').value = ''; toast('再生キューに追加しました'); }));
  $('import-config').addEventListener('click', task(async () => { const value = await invoke('config:import'); if (value) { render(value); renderStyles(); fillConfig(); toast('設定を読み込みました'); } }));
  $('queue-filter').addEventListener('change', renderJobs);
  api.subscribe(render);
  task(async () => { render(await invoke('state')); if (navigator.mediaDevices?.enumerateDevices) { const devices = await navigator.mediaDevices.enumerateDevices(); for (const device of devices.filter(d => d.kind === 'audiooutput' && d.deviceId)) { const option = node('option', device.label || device.deviceId); option.value = device.deviceId; $('output-device').append(option); } fillConfig(); } })();
})();
